title: Juste Djabakou
author:
  name: Juste Djabakou
  email: juste.djabakou@umontreal.ca
  links:
    #- label: "Université de Montréal"
     # icon: "fas fa-university"
      #url: "https://sceco.umontreal.ca/english/home/"
    #- label: "Email me"
      # icon: "fas fa-fw fa-envelope-square" #"fas fa-envelope fa-2x" # le 2x c'est la taille, donc 4x c'est plus grand
        # je peux mettre "fas fa-envelope" aussi qui est enveloppe pleine
        # s pour solid, r regular, l pour light, d pour duotone
      # url: mailto:juste.djabakou@umontreal.ca
    - label: Linkedin
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/juste-djabakou/"
    - label: Website
      icon: "fas fa-fw fa-link"
      # url: "https://justedjabakou.github.io"
    - label: GitHub
      icon: "fab fa-fw fa-github"
      url: "https://github.com/justedjabakou"
    - label: Twitter
      icon: "fab fa-fw fa-twitter-square" #"fab fa-twitter fa-2x" 
      url: "https://twitter.com/justejoseph/"
    - label: Facebook
      icon: "fab fa-fw fa-facebook-square"
      # url: "https://facebook.com/"
      

# The `>` after `description:` means to ignore line-breaks until next key.
# If you want to omit the line-break after the end of text, use `>-` instead.
description: >
  Ph.D. Candidate, Economics. U. of Montreal.    
  Macroeconomics, Firm Dynamics, Finance.

# Build settings

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Theme-specific settings

minima:
  # Minima date format.
  # Refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this.
  #
  # date_format: "%b %-d, %Y"

  # Generate social links in footer.
  #
  social_links:
  #   - { platform: devto,          user_url: "https://dev.to/jekyll" }
  #   - { platform: dribbble,       user_url: "https://dribbble.com/jekyll" }
  #   - { platform: facebook,       user_url: "https://www.facebook.com/jekyll" }
  #   - { platform: flickr,         user_url: "https://www.flickr.com/photos/jekyll" }
    - { platform: github,         user_url: "https://github.com/justedjabakou" }
  #   - { platform: google_scholar, user_url: "https://scholar.google.com/citations?user=qc6CJjYAAAAJ" }
  #   - { platform: instagram,      user_url: "https://www.instagram.com/jekyll" }
  #   - { platform: keybase,        user_url: "https://keybase.io/jekyll" }
    - { platform: linkedin,       user_url: "https://www.linkedin.com/in/juste-djabakou/" }
  #   - { platform: microdotblog,   user_url: "https://micro.blog/jekyll" }
  #   - { platform: pinterest,      user_url: "https://www.pinterest.com/jekyll" }
  #   - { platform: stackoverflow,  user_url: "https://stackoverflow.com/users/1234567/jekyll" }
  #   - { platform: telegram,       user_url: "https://t.me/jekyll" }
    - { platform: x,        user_url: "https://x.com/justejoseph" }
  #   - { platform: x,              user_url: "https://x.com/jekyllrb" }
  #   - { platform: youtube,        user_url: "https://www.youtube.com/jekyll" }

# If you want to link only specific pages in your header, uncomment this and add the path to the pages in
# order as they should show up.
#
# header_pages:
#   - about.md

# Set to `true` to show excerpts on the homepage.
#
# show_excerpts: false

googleanalytics: "G-VHESVBXSY6"

# social links
linkedin_username: juste-djabakou
github_username:  justedjabakou
twitter_username: justejoseph
# rss: rss
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jekyll
# pinterest_username: jekyll
# youtube_username: jekyll
# googleplus_username: +jekyll
# googlegroups_username: jekyll
